# Site settings
baseurl = "https://remaps.yuyangc.me"
languageCode = "en-us"
sectionPagesMenu = "main"
theme = "frances"
googleAnalytics = "UA-167349842-3"

[params]
	name = "remaps"
	description = "A list of applications/ dev tools for the reMarkable paper tablet."
	author = "remaps"
	copyrightname = "Yu Yang Chee"